# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5hfycke3JmFtizyXtVhlvX12Z4GVJ8U
"""

# Question 1
a=int(input("enter number to check: "))
if(a%2==0):
    print("number is even")
else:
    print("number is odd")

# Question 2
a=int(input("enter first number: "))
b=int(input("enter second number: "))
c=int(input("enter third number: "))
if(a>b and b>c):
    print(a,"is greater")
elif(b>a and a>c):
    print("",b,"is greater")
else:
    print(c,"is greater")

# Question 3
year=int(input("enter year: "))
if(year%4==0 and (year%100!=0 or year%400==0)):
    print(year,"is a leap year")
else:
    print(year,"is not a leap year")

# Question 4
per=int(input("enter percentage: "))
if(per>=90):
    print("Grade A")
elif(per>=80 and per<90):
    print("Grade B")
elif(per>=70 and per<80):
    print("Grade C")
elif(per>=60 and per<70):
    print("Grade D")
elif(per<60):
    print("Grade E")
else:
    print("invalid")

# Question 5
char=input("enter character: ")
if(char=='a' or char=='e' or char=='i' or char=='o' or char=='u' or char=='A' or char=='E' or char=='I' or char=='O' or char=='U'):
    print(char,"is a vowel")
else:
  print("Consonant")

# Question 6
b=int(input("enter first number: "))
c=int(input("enter second number: "))
a=input("select the operation(+, -, *, /)")
if(a=='+'):
    print(b+c)
elif(a=='-'):
    print(b-c)
elif(a=='*'):
    print(b*c)
elif(a=='/'):
    print(b/c)

# Question 7
num=int(input("enter number: "))
if(num>0):
    print("positive")
elif(num<0):
    print("negative")
else:
    print("zero")

# Question 8
user="admin"
pas="1234"
username=input("enter username: ")
password=input("enter password: ")
if(username==user and password==pas):
    print("login successful")
else:
    print("login failed")

# Question 9
a=int(input("enter first side: "))
b=int(input("enter second side: "))
c=int(input("enter third side: "))
if((a + b > c) and (b + c > a) and (a + c > b))
    print("triangle is valid")
else:
    print("triangle is invalid")

# Question 10
weight=int(input("enter weight: "))
height=int(input("enter height: "))
bmi=weight/(height*height)
if(bmi<18.5):
    print("underweight")
elif(bmi>=18.5 and bmi<25):
    print("normal weight")
elif(bmi>=25 and bmi<30):
    print("overweight")
elif(bmi>=30):
    print("obesity")
else:
  print("Enter valid input")

# Question 11
price=int(input("enter price: "))
if(price>1000):
    print("10% discount applied")
    print("actual price:", price)
    print("discounted price:", price-(price*0.1))
elif(price<1000 and price>500):
    print("5% discount applied")
    print("actual price:", price)
    print("discounted price:", price-(price*0.05))
else:
  print("no discount applied")
  print("actual price:", price)

# Question 12
month=input("enter month: ")
if(month=="january" or month=="march" or month=="may" or month=="july" or month=="august" or month=="october" or month=="december"):
    print("31 days")
elif(month=="april" or month=="june" or month=="september" or month=="november"):
    print("30 days")
elif(month=="february"):
    print("28/29 days")
else:
  print("invalid month name:")

# Question 13
total_balance=500000
a=int(input("Press 1 for check balance and 2 for deposit and 3 for withdrawl: "))
if(a==1):
    print("your balance is:", total_balance)
elif(a==2):
    b=int(input("enter amount to deposit: "))
    total_balance=total_balance+b
    print("your balance is:", total_balance)
elif(a==3):
    c=int(input("enter amount to withdrawl: "))
    if(c>total_balance):
        print("insufficient balance")
    else:
        total_balance=total_balance-c
        print("your balance is:", total_balance)

# Question 14
age=int(input("enter your age: "))
if(0<age<1):
  print("infact")
elif(2<age<4):
  print("toddler")
elif(4<age<13):
  print("child")
elif(13<age<19):
  print("teenager")
elif(19<age<60):
  print("adult")
else:
  print("senior")

# Question 15
a=int(input("enter number(1-7)"))
if(a==1):
    print("monday")
elif(a==2):
    print("tuesday")
elif(a==3):
    print("wednesday")
elif(a==4):
    print("thursday")
elif(a==5):
    print("friday")
elif(a==6):
    print("saturday")
elif(a==7):
    print("sunday")
else:
  print("invalid input")