# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B10t-t2nwaeRXH-qCJYq0eAOxeF7Ihwu
"""

#python -> python is a general purposee , interpreted programminng language which was invented in 1991 by gudio van rossoum
#for check version
#python --version

#fundamental of python
# 1. variable
# 2. data type
# 3. input(), print()

# variable--> this is a container in which we will store values or assin the vallues

a=56
b=56.3
c="prakul"
# here a,b,c are the variables

# a. global variable ---->entirely modify
# b. local variable ----->specific block of code modify

# data types->
# a. integer --> all positive and negetive values
# b0. float --> all decimal values
# c.  string --> all statement in quotes
# d. boolean ---> true false

#type() function is used to check the data type of any variable

# type casting --> using type csting we can convert or change values from one type to another data type
a=12
b=12.3
c='prakul'
print(type(a))
print(type(b))
print(type(c))

#print() function is used to print the statement and query
#input () function is used to input the values or string from user
#it will take query and send it to function and by default it output will be string

a= input("wnter a number")
b= input("wnter a number")
print(a+b)

a= int(input("wnter a number"))
b= int(input("wnter a number"))
print(a+b)
##here we use type casting

# commanly used operator in python

#add(+)
#subtract(-)
#multiply(*)
#dividion(/) gives float value
#floar division(//) gives round off of division
#modular(%) gives reminder
# equal to(=) used for assign the values to variable
#double equal to (==) used to compare the values
# not equal to (!=)
#greator than (>)
#greator than or equal to (>=)
#less than (<)
#less than equal to(<=)

#CONDITIONAL STATEMENT IN PYTHON
# if
# elif
# else

#ex 1
print ("we provide tthese items : pizza burgur ice cream sandwich ")
print ("pizza=100, burgur =50, ice cream=50 , sandwich=100")

a = input ("enter your item ")
if (a== "pizza" ):
     print("pizza is available ")
     b= int (input ("enter the quantity"))
     c=b*100
     if (c>=2000):
        print("actual price is :", c)
        print ("your discounted price is ",c-(c*0.2))
     elif (1000<c<2000):
        print("actual price is :", c)
        print ("your discounted price is ",c-(c*0.1))

# loops in python
# 1. for loop
# 2. while loop

# (1). for loop
# index = 0 , length = 1
# starting_values will include and last_values will exclude
# by default it start with zero and have a default gap of one
# for example

for i in range(3):
     for j in range(2):
        print(f"i={i} j={j}")

for i in range (0,6):
  print(i* "*")

for i in range(1,6):
    if i==1 or i==5:
        print("* "*i)
    else:
        print("* "+"  "*(i-2)+"*")

n=int(input( "enter the number " ))
for i in range(1,n):
  print("  "*(n-i)+" *"*(2*i-1))

#while loop

#(a). Initilazation
#(b). Condition
#(c). Incriment and Decrement

# print 1 to 4 number using while loop
i=1
while i<=4:
    print(i)
    i=i+1

"""step 1 --->(i=1 ,i<=4) while true
it print the value
same as when i =2,3,4
it print the values
when i = 5 condition false
it exit the loop and give the output
"""

i = int (input("enter first number "))
n = int (input("enter last number "))
p = int (input("enter gap between number "))
while i<=n:
    print(i)
    i=i+p

while (5>=1):
  print(i)
  i=i-1

# write a program in pythonn to get the sum of the number
i=1
n=2
sum =0
while(i<=n):
  sum= sum +i
  i=i+1
print(sum)

a= int (input("Enter first value for commpare:"))
b= int (input("Enter second value for commpare:"))
c= int (input("Enter third value for commpare:"))
if(a<b and b<c):
  print("a contain the minimum value", a)
elif(b<a and a<c):
  print("b contain the minimum value", b)
else:
  print("c contain the minimum value:", c)

a = int(input("enter value"))
if(a%2==0):
  print("hii")
elif(a%5==0):
  print("hello")
else:
  print("bye")

age=int(input("enter your age: "))
if(age<10):
  print("baby")
elif(age>=10 and age<18):
  print("child")
elif(age>=18 and age<30):
  print("adult")
elif(age>=30 and age<60):
  print("mature")
elif(age>=60):
  print("old cititen")
else:
  print("infand")

age = int(input("enter your age: "))
if (age >5):
  print("aadhar card created")
  if (age >18):
    print ("aadhar and pan card is linked")
  else:
    print("pan card is not created")
else:
  print("age is small")

a = int(input("enter number: "))
if (a%2==0):
  if(a%3==0):
    print("number is divisible by 6")
  else:
    print("number is divisible by 2")
else:
  print("number is not divisable")

"""slicing in python is defined as to sice the string as wee want the range
index is the position of every character in the given string such as in


"""

city="Rajasthan"
print(city[0:5])
print(city[5:11])
print(city[2:7:-1])

11//2+5-1

"""BITWISE OPERATOR

                  8  4  2  1
11                1  0  1  1
14                1  1  1  0
______________________________________
bitwise and                   1     1
11 & 14
OUTPUT IS 10
"""

11 & 14

13 & 7

"""there are seven operator in python
arithmatic(+, - ,* / ,// )
bitwise( & ,| , << , >>)
logicial( and or not)
assignment( equal to(=))
comparison ( < ,> ,<=,>= ,== ,!=)
identity (
"""

for i in range (50,9,-1):
  print(i)

a = 0
for i in range (1,11):
  a=a+i
print(a)

count=0
for i in range(69,3,-1):
   count=count+1
print(count)

for i in range (1,14):
  if(i%3==0):
    print(i)

even_sum=0
odd_sum=0
for i in range (55,22,-1):
  if(i%2==0):
    even_sum=even_sum+i
  else:
    odd_sum=odd_sum+i
print("even sum ",even_sum)
print("odd sum ",odd_sum)

